
# project_id should always be the first line!
project_id = "kmggxfzruwitzlwcifdr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true
double_confirm_changes = true
double_confirm_deletions = true

[realtime]
enabled = true

[functions]
[functions.create-razorpay-order]
verify_jwt = true
