
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmggxfzruwitzlwcifdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ2d4ZnpydXdpdHpsd2NpZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTkzNDIsImV4cCI6MjA2MDAzNTM0Mn0.pptc-W4Xn8lzRhfACDywbr1NalKcthxeXk-dbbekfAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
